"""V3 memory provider abstractions.

Port of `atomicmemory-sdk/src/memory/`. Defines the core types and
provider interfaces; concrete providers live in
`atomicmemory.providers`.
"""

from atomicmemory.memory.filters import FieldFilter, FieldFilterOp, FilterExpr
from atomicmemory.memory.types import (
    Capabilities,
    CapabilitiesExtensions,
    CapabilitiesRequiredScope,
    ContextPackage,
    GraphEdge,
    GraphNode,
    GraphResult,
    GraphSearchRequest,
    HealthStatus,
    IngestBase,
    IngestInput,
    IngestResult,
    Insight,
    ListRequest,
    ListResultPage,
    Memory,
    MemoryKind,
    MemoryRef,
    MemoryVersion,
    MemoryVersionEvent,
    Message,
    MessageIngest,
    MessageRole,
    PackageFormat,
    PackageRequest,
    Profile,
    Provenance,
    Scope,
    SearchRequest,
    SearchResult,
    SearchResultPage,
    TextIngest,
    VerbatimIngest,
)

__all__ = [
    "Capabilities",
    "CapabilitiesExtensions",
    "CapabilitiesRequiredScope",
    "ContextPackage",
    "FieldFilter",
    "FieldFilterOp",
    "FilterExpr",
    "GraphEdge",
    "GraphNode",
    "GraphResult",
    "GraphSearchRequest",
    "HealthStatus",
    "IngestBase",
    "IngestInput",
    "IngestResult",
    "Insight",
    "ListRequest",
    "ListResultPage",
    "Memory",
    "MemoryKind",
    "MemoryRef",
    "MemoryVersion",
    "MemoryVersionEvent",
    "Message",
    "MessageIngest",
    "MessageRole",
    "PackageFormat",
    "PackageRequest",
    "Profile",
    "Provenance",
    "Scope",
    "SearchRequest",
    "SearchResult",
    "SearchResultPage",
    "TextIngest",
    "VerbatimIngest",
]
