"""V3 memory provider abstractions.

Port of `atomicmemory-sdk/src/memory/`. Defines the core types and
provider interfaces; concrete providers live in
`atomicmemory.providers`.
"""

from atomicmemory.memory.capability_profiles import (
    CapabilityGap,
    CapabilityProfile,
    capability_gaps,
    satisfies_profile,
)
from atomicmemory.memory.filters import FieldFilter, FieldFilterOp, FilterExpr
from atomicmemory.memory.meta_fact_filter import (
    DEFAULT_META_FACT_PATTERNS,
    MetaFactFilterConfig,
    filter_meta_facts,
    is_meta_fact,
    resolve_meta_fact_patterns,
)
from atomicmemory.memory.pipeline import (
    NOOP_ASYNC_PIPELINE,
    NOOP_PIPELINE,
    AsyncMemoryProcessingPipeline,
    MemoryProcessingPipeline,
)
from atomicmemory.memory.types import (
    Capabilities,
    CapabilitiesExtensions,
    CapabilitiesRequiredScope,
    ContentClass,
    ContextPackage,
    GraphEdge,
    GraphNode,
    GraphResult,
    GraphSearchRequest,
    HealthStatus,
    IngestBase,
    IngestInput,
    IngestResult,
    Insight,
    ListRequest,
    ListResultPage,
    Memory,
    MemoryKind,
    MemoryRef,
    MemoryVersion,
    MemoryVersionEvent,
    Message,
    MessageIngest,
    MessageRole,
    PackageFormat,
    PackageRequest,
    Profile,
    Provenance,
    RetrievalReceipt,
    Scope,
    SearchRequest,
    SearchResult,
    SearchResultPage,
    TextIngest,
    VerbatimIngest,
)

__all__ = [
    "DEFAULT_META_FACT_PATTERNS",
    "NOOP_ASYNC_PIPELINE",
    "NOOP_PIPELINE",
    "AsyncMemoryProcessingPipeline",
    "Capabilities",
    "CapabilitiesExtensions",
    "CapabilitiesRequiredScope",
    "CapabilityGap",
    "CapabilityProfile",
    "ContentClass",
    "ContextPackage",
    "FieldFilter",
    "FieldFilterOp",
    "FilterExpr",
    "GraphEdge",
    "GraphNode",
    "GraphResult",
    "GraphSearchRequest",
    "HealthStatus",
    "IngestBase",
    "IngestInput",
    "IngestResult",
    "Insight",
    "ListRequest",
    "ListResultPage",
    "Memory",
    "MemoryKind",
    "MemoryProcessingPipeline",
    "MemoryRef",
    "MemoryVersion",
    "MemoryVersionEvent",
    "Message",
    "MessageIngest",
    "MessageRole",
    "MetaFactFilterConfig",
    "PackageFormat",
    "PackageRequest",
    "Profile",
    "Provenance",
    "RetrievalReceipt",
    "Scope",
    "SearchRequest",
    "SearchResult",
    "SearchResultPage",
    "TextIngest",
    "VerbatimIngest",
    "capability_gaps",
    "filter_meta_facts",
    "is_meta_fact",
    "resolve_meta_fact_patterns",
    "satisfies_profile",
]
