"""atomicmemory — Python client SDK for AtomicMemory.

Top-level re-exports for the public API. Users typically only need to
import `AtomicMemoryClient` plus the type they're working with — every
type they could need is re-exported here.
"""

from atomicmemory._version import __version__
from atomicmemory.client.async_memory_client import AsyncMemoryClient, AsyncProviderStatus
from atomicmemory.client.atomic_memory_client import (
    AsyncAtomicMemoryClient,
    AtomicMemoryClient,
    AtomicMemoryClientConfig,
    MemoryNamespaceConfig,
)
from atomicmemory.client.memory_client import MemoryClient, ProviderStatus
from atomicmemory.core.errors import (
    AtomicMemoryError,
    ConfigError,
    NetworkError,
    NotInitializedError,
    ProviderError,
    RateLimitError,
    ValidationError,
)
from atomicmemory.memory.filters import FieldFilter, FieldFilterOp, FilterExpr
from atomicmemory.memory.types import (
    Capabilities,
    CapabilitiesExtensions,
    CapabilitiesRequiredScope,
    ContextPackage,
    GraphEdge,
    GraphNode,
    GraphResult,
    GraphSearchRequest,
    HealthStatus,
    IngestBase,
    IngestInput,
    IngestResult,
    Insight,
    ListRequest,
    ListResultPage,
    Memory,
    MemoryKind,
    MemoryRef,
    MemoryVersion,
    MemoryVersionEvent,
    Message,
    MessageIngest,
    MessageRole,
    PackageFormat,
    PackageRequest,
    Profile,
    Provenance,
    Scope,
    SearchRequest,
    SearchResult,
    SearchResultPage,
    TextIngest,
    VerbatimIngest,
)
from atomicmemory.storage import (
    ArtifactHead,
    ArtifactInUseError,
    ArtifactMetadata,
    ArtifactNotFoundError,
    ArtifactRange,
    ArtifactRef,
    AsyncStorageClient,
    DeleteArtifactOptions,
    DeleteArtifactPolicy,
    DeleteArtifactResult,
    FilecoinDirectStorageNotSupportedError,
    PointerContentNotManagedError,
    PutArtifactInput,
    PutManagedInput,
    PutPointerInput,
    StorageArtifactStatus,
    StorageCapabilities,
    StorageClient,
    StorageClientConfig,
    StorageClientError,
    StoredArtifact,
    UnsupportedCapabilityError,
    VerificationResult,
    VerifyArtifactOptions,
)

__all__ = [
    "ArtifactHead",
    "ArtifactInUseError",
    "ArtifactMetadata",
    "ArtifactNotFoundError",
    "ArtifactRange",
    "ArtifactRef",
    "AsyncAtomicMemoryClient",
    "AsyncMemoryClient",
    "AsyncProviderStatus",
    "AsyncStorageClient",
    "AtomicMemoryClient",
    "AtomicMemoryClientConfig",
    "AtomicMemoryError",
    "Capabilities",
    "CapabilitiesExtensions",
    "CapabilitiesRequiredScope",
    "ConfigError",
    "ContextPackage",
    "DeleteArtifactOptions",
    "DeleteArtifactPolicy",
    "DeleteArtifactResult",
    "FieldFilter",
    "FieldFilterOp",
    "FilecoinDirectStorageNotSupportedError",
    "FilterExpr",
    "GraphEdge",
    "GraphNode",
    "GraphResult",
    "GraphSearchRequest",
    "HealthStatus",
    "IngestBase",
    "IngestInput",
    "IngestResult",
    "Insight",
    "ListRequest",
    "ListResultPage",
    "Memory",
    "MemoryClient",
    "MemoryKind",
    "MemoryNamespaceConfig",
    "MemoryRef",
    "MemoryVersion",
    "MemoryVersionEvent",
    "Message",
    "MessageIngest",
    "MessageRole",
    "NetworkError",
    "NotInitializedError",
    "PackageFormat",
    "PackageRequest",
    "PointerContentNotManagedError",
    "Profile",
    "Provenance",
    "ProviderError",
    "ProviderStatus",
    "PutArtifactInput",
    "PutManagedInput",
    "PutPointerInput",
    "RateLimitError",
    "Scope",
    "SearchRequest",
    "SearchResult",
    "SearchResultPage",
    "StorageArtifactStatus",
    "StorageCapabilities",
    "StorageClient",
    "StorageClientConfig",
    "StorageClientError",
    "StoredArtifact",
    "TextIngest",
    "UnsupportedCapabilityError",
    "ValidationError",
    "VerbatimIngest",
    "VerificationResult",
    "VerifyArtifactOptions",
    "__version__",
]
